const $=id=>document.getElementById(id);function page(p){document.querySelectorAll('.page').forEach(x=>x.classList.remove('active'));$(p).classList.add('active')}
async function api(u,o){let r=await fetch(u,o);if(!r.ok)throw Error(await r.text());return r.json()}
async function refresh(){let d=await api('/api/dashboard');$('flows').textContent=d.flows;$('detections').textContent=d.detections;$('critical').textContent=d.critical;$('open').textContent=d.open_incidents}
async function upload(){let f=$('pcap').files[0];if(!f)return alert('Choose a PCAP');let fd=new FormData();fd.append('file',f);$('pcapOut').textContent='Analyzing...';try{$('pcapOut').textContent=JSON.stringify(await api('/api/pcap',{method:'POST',body:fd}),null,2);refresh()}catch(e){$('pcapOut').textContent=e.message}}
async function analyze(){let p=+$('packets').value,s=+$('syn').value,a=+$('ack').value;let f={src_ip:$('src').value,dst_ip:$('dst').value,protocol:'TCP',src_port:50000,dst_port:+$('dport').value,packet_count:p,byte_count:p*600,duration:1,packets_per_sec:p,bytes_per_sec:p*600,syn_count:s,ack_count:a,rst_count:0,fin_count:0};$('result').textContent=JSON.stringify(await api('/api/analyze-flow',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(f)}),null,2);refresh()}
async function subnet(){$('subnetOut').textContent=JSON.stringify(await api('/api/cn/subnet?cidr='+encodeURIComponent($('cidr').value)),null,2)}
async function perf(){$('perfOut').textContent=JSON.stringify(await api(`/api/cn/performance?size_mb=${$('size').value}&bandwidth_mbps=${$('bandwidth').value}&rtt_ms=${$('rtt').value}`),null,2)}
async function incidents(){let a=await api('/api/incidents');$('incidentList').innerHTML=a.map(x=>`<div class="row ${x.severity==='critical'?'danger':'warn'}"><b>${x.attack_type}</b> — ${x.severity} — score ${x.threat_score}<br>${x.src_ip} → ${x.dst_ip}<br>${x.explanation}</div>`).join('')||'No incidents.'}
async function cn(){let o=await api('/api/cn/osi');$('osi').innerHTML=o.map(x=>`<div class="layer"><b>L${x.layer} — ${x.name}</b><br>${x.examples}<br><small>${x.purpose}</small></div>`).join('');let p=await api('/api/cn/protocols');$('protocols').innerHTML=p.map(x=>`<div class="layer"><b>${x.name}</b> — L${x.layer}<br>${x.purpose}<br><small>${x.key}</small></div>`).join('');$('routing').textContent=JSON.stringify(await api('/api/cn/routing'),null,2);$('congestion').textContent=JSON.stringify(await api('/api/cn/congestion'),null,2)}
function connect(){let w=new WebSocket(`${location.protocol==='https:'?'wss':'ws'}://${location.host}/ws/alerts`);w.onmessage=e=>{let x=JSON.parse(e.data),d=document.createElement('div');d.className='row danger';d.textContent=`${x.attack_type} | ${x.severity} | ${x.src_ip} → ${x.dst_ip} | score ${x.score}`;$('alerts').prepend(d);refresh()};w.onclose=()=>setTimeout(connect,3000)}refresh();cn();connect();